[project]
name = "evaluatio-docs"
version = "0.0.0"
requires-python = ">=3.12"

dependencies = [
    "jupyter-book>=2.0.0",
    "evaluatio",
]

[tool.uv.sources]
evaluatio = { path = "../" }

[tool.uv]
package = false
